CREATE TABLE SAGA
(
    ID   INT          NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID)
);


create table VIDEOGAME
(
    ID    INT          NOT NULL AUTO_INCREMENT,
    TITLE VARCHAR(100) NOT NULL,
    SAGA_ID INT,
    PRIMARY KEY (ID),
    CONSTRAINT fk_SAGA_ID_VIDEOGAME
        FOREIGN KEY (SAGA_ID)
            REFERENCES SAGA (ID)
);

create table PROMOTION
(
    ID           int not null AUTO_INCREMENT,
    VALID_FROM   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRICE        numeric(5, 2),
    VIDEOGAME_ID int not null,
    PRIMARY KEY (ID),
    CONSTRAINT fk_VIDEOGAME_ID_PROMOTION
        FOREIGN KEY (VIDEOGAME_ID)
            REFERENCES VIDEOGAME (ID)
);


create table STOCK
(
    ID      INT        not null AUTO_INCREMENT,
    AVAILABILITY boolean,
    LAST_UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    VIDEOGAME_ID int        not null,
    PRIMARY KEY (ID),
    CONSTRAINT fk_VIDEOGAME_ID_STOCK
        FOREIGN KEY (VIDEOGAME_ID)
            REFERENCES VIDEOGAME (ID)
);





