openapi: 3.0.0
info:
  title: VideoGamesAPI
  version: '1.0'
servers:
  - url: 'http://localhost:8080'
paths:
  '/game/{gameId}/saga':
    get:
      parameters:
        - name: gameId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Sagas'
components:
  schemas:
    Sagas:
      type: array
      description: 'List of game sagas related to a given game ordered by relevance'
      minItems: 0
      uniqueItems: true
      items:
        $ref: '#/components/schemas/Game'
    Game:
      description: 'Game detail'
      type: object
      properties:
        id:
          type: string
          minLength: 1
        title:
          type: string
          minLength: 1
        genre:
          type: string
        releaseDate:
          type: string
          format: date
      required:
        - id
        - title
        - genre
        - releaseDate
    VideoGameResponse:
      type: object
      properties:
        videoGameId:
          type: integer
          example: 1
        price:
          type: number
          format: float
          example: 99.99
        tittle:
          type: string
          format: date-time
          example: 'Wasteland Chronicles: Edge of Survival'
    ErrorResponse:
      type: object
      properties:
        status:
          type: integer
          example: 404
        message:
          type: string
          example: Invalid request parameters