openapi: 3.0.0
info:
  title: gameSagaAPI
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
tags:
  - name: GameSagas
    description: The videogames saga endpoint
paths:
  '/game-saga/{sagaId}/related-sagas':
    parameters:
      - schema:
          type: integer
        name: sagaId
        in: path
        required: true
    get:
      tags:
        - GameSagas
      operationId: get-game-saga-related-sagas
      summary: Gets the related game sagas
      description: Returns the related game sagas to a given one ordered by relevance
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VideoGameSagaResponse'
components:
  schemas:
    VideoGameSagaResponse:
      type: array
      items:
        type: object
        properties:
          videoGameId:
            type: long
            example: 1
          price:
            type: number
            format: double
            example: 99.9
          title:
            type: string
            example: 'Wasteland Chronicles: Edge of Survival'
          stock:
            type: boolean
            example: true
        required:
          - videoGameId
          - price
          - title
          - stock

