openapi: 3.0.0
info:
  title: VideoGamesAPI
  version: '1.0'
servers:
  - url: 'http://localhost:8080'
tags:
  - name: Game
    description: The videogames endpoint
paths:
  '/game/{gameId}/saga':
    get:
      parameters:
        - name: gameId
          in: path
          required: true
          schema:
            type: string
      tags:
        - name: Game
          operationId: get-game-saga
          summary: Gets the related game by id
          description: Returns the related game
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VideoGameResponse'
components:
  schemas:
    Game:
      description: 'Game detail'
      type: object
      properties:
        id:
          type: integer
          minLength: 1
        title:
          type: string
          minLength: 1
      required:
        - id
        - title
    VideoGameResponse:
      type: object
      properties:
        game:
          $ref: '#/components/schemas/Game'
    ErrorResponse:
      type: object
      properties:
        status:
          type: integer
          example: 404
        message:
          type: string
          example: Invalid request parameters